title: "Ruby on Rails 入門"
summary: "Ruby on Railsの基礎知識について、まとめました"
topics: ["Ruby", "Rails", "Vue.js", "AWS"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - rails_aws
  - vue_rails_aws
  - vue_rails
  - paiza_method1
  - paiza_method2
  - rails_command

